language: python

python:
    - "3.8"

env:
    - SECRET_KEY='TEST'

install:
    - pip install -r requirements.txt
    - pip install coveralls

script:
    - python manage.py test menu
    - coverage run --source-menu manage.py test menu

after_success: coveralls



