# Generated by Django 3.0.6 on 2020-05-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='isVendor',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='isVendor',
        ),
        migrations.AddField(
            model_name='user',
            name='isVendor',
            field=models.BooleanField(default=False),
        ),
    ]
