# Generated by Django 3.0.6 on 2020-05-12 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField()),
                ('dateTimeCreated', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('isRecurring', models.BooleanField(default=False)),
                ('frequencyOfReocurrence', models.CharField(choices=[('D', 'Daily'), ('B', 'Bi-Weekly'), ('W', 'Weekly'), ('E', 'Weeekend')], default=None, max_length=1, verbose_name='Frequency')),
                ('img_url', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Image')),
                ('vendorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Vendor', verbose_name='vendor')),
            ],
        ),
    ]
