# Generated by Django 3.0.6 on 2020-05-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='frequencyOfReocurrence',
            field=models.CharField(choices=[('E', 'Everyday'), ('M', 'Mondays'), ('T', 'Tuesdays'), ('W', 'Wednesdays'), ('TH', 'Thursdays'), ('F', 'Fridays'), ('WK', 'Weeekends')], default=None, max_length=2, verbose_name='Frequency'),
        ),
    ]
