# Generated by Django 3.0.6 on 2020-05-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200512_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='img_url',
        ),
    ]
