# Generated by Django 3.0.6 on 2020-05-23 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0002_auto_20200519_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsOrdered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('dateTimeCreated', models.DateField(auto_now_add=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='menu.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('S', 'Sent'), ('D', 'Delivered'), ('R', 'Read')], default=None, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amountPaid', models.FloatField(blank=True, null=True)),
                ('dateAndTimeOfOrder', models.DateTimeField(auto_now_add=True)),
                ('amountDue', models.FloatField(blank=True, null=True)),
                ('has_paid', models.BooleanField(default=False)),
                ('dateTimeCreated', models.DateTimeField(auto_now_add=True)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custsomer', to=settings.AUTH_USER_MODEL)),
                ('itemsOrdered', models.ManyToManyField(through='order.ItemsOrdered', to='menu.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('P', 'Proccesing'), ('T', 'In-Transit'), ('C', 'Canceled'), ('D', 'Delivered')], default='B', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.Order')),
                ('expectedDate', models.DateField()),
            ],
            bases=('order.order',),
        ),
        migrations.AddField(
            model_name='order',
            name='orderStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderStatus'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('dateTimeCreated', models.DateTimeField(auto_now_add=True)),
                ('messageStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.MessageStatus')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('subjectUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='itemsordered',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
    ]
